on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Lost Pixel

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test:local

            - name: Lost Pixel
              uses: lost-pixel/lost-pixel@v3.6.0
              env:
                  LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              if: ${{ failure() && steps.lp.conclusion == 'failure' }}
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: update lost-pixel baselines
                  delete-branch: true
                  branch: "lost-pixel-update/${{ github.ref_name }}"
                  title: "Lost Pixel update - ${{ github.ref_name }}"
                  body: Automated baseline update PR created by Lost Pixel
